/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-04-12 04:03:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.customer.togetherBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class togetherUpdateBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"image/icon.ico\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t<script src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=a53c0b810ce1d051d15c474f3785be1d&libraries=services\"></script>\r\n");
      out.write("    <script defer src=\"resources/js/common.js\"></script>\r\n");
      out.write("\t<link href=\"resources/css/togetherUpdate.css?v=");
      out.print(System.currentTimeMillis());
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\t\t<div id=\"updateheader\">글 수정</div>\r\n");
      out.write("\t\t<div id=\"updateForm\">\r\n");
      out.write("\t\t\t<form action=\"t_updateBoard.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t<label for=\"exampleSelect1\">말머리</label>\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" id=\"tHeader\" name=\"tHeader\"  onchange=\"dSearchLocShow(this.value);\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"함께먹어요\">함께 먹어요</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"함께출퇴근해요\">함께 출퇴근해요</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"함께나눠요\">함께 나눠요</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t<label for=\"exampleSelect1\">참여가능 인원수</label>\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" id=\"tJoinMax\" name=\"tJoinMax\">\r\n");
      out.write("\t\t\t\t\t\t   <option>1</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>2</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>3</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>4</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>5</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>6</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>7</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>8</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>9</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>10</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t     \t\t\t<label for=\"tTitle\">제목</label>\r\n");
      out.write("\t    \t\t\t<input type=\"text\" class=\"form-control\" id=\"tTitle\" name=\"tTitle\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("   \t\t\t\t\t<label>모임 장소</label><br>\r\n");
      out.write("                      <input type=\"text\" id=\"searchLoc1\" name=\"tAddress\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><input type=\"button\" id=\"searchBtn1\"\r\n");
      out.write("                          onclick=\"PostCode()\" value=\"주소 검색\" class=\"btn btn-primary\"/>\r\n");
      out.write("                    <div id=\"map\"></div>\r\n");
      out.write("                    <input type=\"hidden\" id=\"tLocX\" name=\"tLocX\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tLocX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                    <input type=\"hidden\" id=\"tLocY\" name=\"tLocY\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tLocY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t  \t\t\t<div class=\"form-inline\" id=\"dSearchLoc\">\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t     \t\t\t<label for=\"tJoinDate\">날짜</label>\r\n");
      out.write("\t    \t\t\t<input type=\"datetime-local\" class=\"form-control\" id=\"tJoinDate\" name=\"tJoinDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tJoinDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"tContent\">내용</label>\r\n");
      out.write("\t\t\t\t\t<textarea class=\"form-control\" id=\"tContent\" name=\"tContent\" cols=\"20\" rows=\"8\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"uploadFile1\">썸네일 첨부</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control-file\" id=\"uploadFile1\" name=\"uploadFile1\" onchange=\"loadFile(event);\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"uploadFile2\">내용사진 첨부</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control-file\" id=\"uploadFile2\" name=\"uploadFile2\" onchange=\"loadFile(event);\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"tNo\" name=\"tNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t<div id=\"updatebutton\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">수정</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" onclick=\"location.href='t_openBoardList.do?tHeader=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tHeader}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" class=\"btn btn-primary\">취소</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write(" <script src=\"resources/js/togetherUpdate.js?v=");
      out.print(System.currentTimeMillis());
      out.write("\"></script>\r\n");
      out.write(" <script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$('#image_preview').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar tHeader = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tHeader}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; \r\n");
      out.write("\t\tvar tJoinMax = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tJoinMax}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tconsole.log(tHeader+\",\"+tJoinMax);\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#tHeader').val(tHeader).attr('selected',true);\r\n");
      out.write("\t\t$('#tJoinMax option:eq('+(tJoinMax-1)+')').attr('selected',true);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar tHeader = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tHeader}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar tLocX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tLocX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar tLocY = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tLocY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar dLocX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tDestinationVO.dLocX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar dLocY = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tDestinationVO.dLocY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tconsole.log(tHeader+\",\"+tLocX+\",\"+tLocY+\",\"+dLocX+\",\"+dLocY);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(tHeader == '함께출퇴근해요'){\r\n");
      out.write("\t\t\tgetCommuteMap();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tgetMap();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getMap(){\r\n");
      out.write("\t\t\tvar mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("\t\t    mapOption = { \r\n");
      out.write("\t\t        center: new kakao.maps.LatLng(tLocX, tLocY), // 지도의 중심좌표\r\n");
      out.write("\t\t        level: 3 // 지도의 확대 레벨\r\n");
      out.write("\t\t    };\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 마커가 표시될 위치입니다 \r\n");
      out.write("\t\t\tvar markerPosition  = new kakao.maps.LatLng(tLocX, tLocY); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 마커를 생성합니다\r\n");
      out.write("\t\t\tvar marker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t    position: markerPosition\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("\t\t\tmarker.setMap(map);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
