/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-04-12 12:45:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.customer.togetherBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Bitcamp/haeyo_2021_04_10_최종/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/haeyo/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1616565092596L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t<script src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=a53c0b810ce1d051d15c474f3785be1d&libraries=services\"></script>\r\n");
      out.write("\t<link href=\"resources/css/togetherBoard/togetherUpdate.css?v=");
      out.print(System.currentTimeMillis());
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\t\t<div id=\"updateheader\">글 수정</div>\r\n");
      out.write("\t\t<div id=\"updateFormBox\">\r\n");
      out.write("\t\t\t<form action=\"t_updateBoard.do\" method=\"post\" enctype=\"multipart/form-data\" id=\"updateForm\">\r\n");
      out.write("\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t<label for=\"exampleSelect1\">말머리</label>\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" id=\"tHeader\" name=\"tHeader\"  onchange=\"dSearchLocShow(this.value);\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"함께먹어요\">함께 먹어요</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"함께출퇴근해요\">함께 출퇴근해요</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"함께나눠요\">함께 나눠요</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t     \t\t\t<label for=\"tTitle\">제목</label>\r\n");
      out.write("\t    \t\t\t<input type=\"text\" class=\"form-control\" id=\"tTitle\" name=\"tTitle\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("   \t\t\t\t\t<label>모임 장소</label><br>\r\n");
      out.write("                      <input type=\"text\" id=\"searchLoc1\" name=\"tAddress\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><input type=\"button\" id=\"searchBtn1\"\r\n");
      out.write("                          onclick=\"PostCode()\" value=\"주소 검색\" class=\"btn btn-primary\"/>\r\n");
      out.write("                    <div id=\"map\"></div>\r\n");
      out.write("                    <input type=\"hidden\" id=\"tLocX\" name=\"tLocX\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tLocX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                    <input type=\"hidden\" id=\"tLocY\" name=\"tLocY\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tLocY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t  \t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t     \t\t\t<label for=\"tJoinDate\">날짜</label>\r\n");
      out.write("\t    \t\t\t<input type=\"datetime-local\" class=\"form-control\" id=\"tJoinDate\" name=\"tJoinDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tJoinDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t  \t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t<label for=\"tJoinMax\">참여가능 인원수</label>\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" id=\"tJoinMax\" name=\"tJoinMax\">\r\n");
      out.write("\t\t\t\t\t\t   <option>1</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>2</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>3</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>4</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>5</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>6</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>7</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>8</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>9</option>\r\n");
      out.write("\t\t\t\t\t\t   <option>10</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"tContent\">내용</label>\r\n");
      out.write("\t\t\t\t\t<textarea class=\"form-control\" id=\"tContent\" name=\"tContent\" cols=\"20\" rows=\"8\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"uploadFile1\">썸네일 첨부</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control-file\" id=\"uploadFile1\" name=\"uploadFile1\" onchange=\"loadFile(event);\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"befoFile1\">이전 파일: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tPic1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"tPic1\"><img class=\"image_preview\" src=\"/WEB-INF/boardImages/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tPic1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" height=\"200\" width=\"350\"></div>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tPic1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"tPicHidden1\" name=\"tPic1\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"uploadFile2\">내용사진 첨부</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" class=\"form-control-file\" id=\"uploadFile2\" name=\"uploadFile2\" onchange=\"loadFile(event);\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"befoFile2\">이전 파일: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tPic2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"tPic2\"><img class=\"image_preview\" src=\"/WEB-INF/boardImages/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tPic2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" height=\"200\" width=\"350\"></div>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tPic2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"tPicHidden2\" name=\"tPic2\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"tNo\" name=\"tNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t<div id=\"updatebutton\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">수정</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" onclick=\"location.href='t_openBoardList.do?tHeader=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tHeader}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" class=\"btn btn-primary\">취소</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write(" <script src=\"resources/js/togetherBoard/togetherUpdate.js?v=");
      out.print(System.currentTimeMillis());
      out.write("\"></script>\r\n");
      out.write(" <script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar tHeader = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tHeader}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; \r\n");
      out.write("\t\tvar tJoinMax = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tJoinMax}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tconsole.log(tHeader+\",\"+tJoinMax);\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#tHeader').val(tHeader).attr('selected',true);\r\n");
      out.write("\t\t$('#tJoinMax option:eq('+(tJoinMax-1)+')').attr('selected',true);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar tHeader = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tHeader}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar tLocX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tLocX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar tLocY = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tLocY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar dLocX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tDestinationVO.dLocX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tvar dLocY = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tDestinationVO.dLocY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\tconsole.log(tHeader+\",\"+tLocX+\",\"+tLocY+\",\"+dLocX+\",\"+dLocY);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(tHeader == '함께출퇴근해요'){\r\n");
      out.write("\t\t\tgetMap();\r\n");
      out.write("\t\t\tgetMap2();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tgetMap();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getMap(){\r\n");
      out.write("\t\t\tvar mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("\t\t    mapOption = { \r\n");
      out.write("\t\t        center: new kakao.maps.LatLng(tLocX, tLocY), // 지도의 중심좌표\r\n");
      out.write("\t\t        level: 3 // 지도의 확대 레벨\r\n");
      out.write("\t\t    };\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 마커가 표시될 위치입니다 \r\n");
      out.write("\t\t\tvar markerPosition  = new kakao.maps.LatLng(tLocX, tLocY); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 마커를 생성합니다\r\n");
      out.write("\t\t\tvar marker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t    position: markerPosition\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t// 지도를 보여준다.\r\n");
      out.write("            mapContainer.style.display = \"block\";\r\n");
      out.write("\t\t\t// 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("\t\t\tmarker.setMap(map);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getMap2(){\r\n");
      out.write("\t\t\tvar mapContainer2 = document.getElementById('map2'), // 지도를 표시할 div \r\n");
      out.write("\t\t    mapOption = { \r\n");
      out.write("\t\t        center: new kakao.maps.LatLng(dLocX, dLocY), // 지도의 중심좌표\r\n");
      out.write("\t\t        level: 3 // 지도의 확대 레벨\r\n");
      out.write("\t\t    };\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar map2 = new kakao.maps.Map(mapContainer2, mapOption); // 지도를 생성합니다\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 마커가 표시될 위치입니다 \r\n");
      out.write("\t\t\tvar markerPosition  = new kakao.maps.LatLng(dLocX, dLocY); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 마커를 생성합니다\r\n");
      out.write("\t\t\tvar marker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t    position: markerPosition\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("\t\t\tmapContainer2.style.display = \"block\";\r\n");
      out.write("\t\t\tmap2.relayout();\r\n");
      out.write("\t\t\tmarker.setMap(map);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/customer/togetherBoard/updateBoard.jsp(34,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tHeader == '함께출퇴근해요'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t  \t\t\t<div class=\"form-inline\" id=\"dSearchLoc\">\r\n");
          out.write("\t   \t\t\t\t\t<label>도착 장소</label><br>\r\n");
          out.write("\t                      <input type=\"text\" id=\"searchLoc2\" name=\"dAddress\" class=\"form-control\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tDestinationVO.dAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/><input type=\"button\" id=\"searchBtn1\"\r\n");
          out.write("\t                          onclick=\"PostCode2()\" value=\"주소 검색\" class=\"btn btn-primary\"/>\r\n");
          out.write("\t                    <div id=\"map2\"></div>\r\n");
          out.write("\t                    <input type=\"hidden\" id=\"dLocX\" name=\"dLocX\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tDestinationVO.dLocX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("\t                    <input type=\"hidden\" id=\"dLocY\" name=\"dLocY\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.tDestinationVO.dLocY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("\t\t  \t\t\t</div>\r\n");
          out.write("\t\t  \t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
