/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-04-10 10:00:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.haeyo.biz.user.impl.UserDAOMybatis;
import com.haeyo.biz.user.UserVO;
import java.net.URLEncoder;
import java.security.SecureRandom;
import java.math.BigInteger;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Bitcamp/haeyo_2021_04_10_최종/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/haeyo/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1616565092596L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.haeyo.biz.user.impl.UserDAOMybatis");
    _jspx_imports_classes.add("java.security.SecureRandom");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("com.haeyo.biz.user.UserVO");
    _jspx_imports_classes.add("java.math.BigInteger");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String errMsg = (String) session.getAttribute("errMsg");
if (errMsg == null)
	errMsg = "";

session.invalidate();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link href=\"resources/image/icon.ico\" rel=\"shortcut icon\"\r\n");
      out.write("\ttype=\"image/x-icon\">\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<link href=\"resources/css/login.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"resources/css/header.css\" rel=\"stylesheet\">\r\n");
      out.write("<script defer src=\"resources/js/login.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		session = request.getSession();
	UserVO user = (UserVO) session.getAttribute("user");
	
      out.write("\r\n");
      out.write("\t<wrap> <!--modalStart-->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\"\r\n");
      out.write("\t\trole=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\"\r\n");
      out.write("\t\taria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalCenterTitle\">어떤 서비스를\r\n");
      out.write("\t\t\t\t\t\t원하시나요?</h5>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"location.href='#.jsp'\">수 리</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-secondary\">이 사</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn-secondary\">청 소</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--modalEnd--> <!------- headerStart -------> <header id=\"header\">\r\n");
      out.write("\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t<logo id=\"logo\"> <a href=\"/project/\"><img\r\n");
      out.write("\t\t\t\tsrc=\"resources/image/logo2.png\" alt=\"로고\"></a> </logo>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">같이해요</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">혼자해요</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">전문가 신청</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-toggle bell\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"fas fa-bell\"></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right alarm1\">\r\n");
      out.write("\t\t\t\t\t\t<p>알림</p>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"alarmTxt\">회원님이 결제를 완료하셨습니다.</div>\r\n");
      out.write("\t\t\t\t\t\t<span>23분전</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\">회원님</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\" id=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"profiteTxt\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>반갑습니다! </span>회원님\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"profileMenu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fas fa-user menuico\"></i>마이페이지</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fas fa-sign-out-alt menuico\"></i>로그아웃</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fas fa-exchange-alt menuico\"></i>전문가로 전환</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header> <!------- headerEND -------> <!------- loginStart -------> <!-- <form action=\"login.do\" method=\"post\"> -->\r\n");
      out.write("\t<form action=\"login.do\" name=form method=\"post\"\r\n");
      out.write("\t\tonsubmit=\"return Login_proc.jsp();\">\r\n");
      out.write("\t\t<!-- <form action=\"login.do\" name=form method=\"post\"\r\n");
      out.write("\t\tonsubmit=\"return login_check();\"> -->\r\n");
      out.write("\t\t<div id=\"login-body\">\r\n");
      out.write("\t\t\t<div id=\"login_title\">\r\n");
      out.write("\t\t\t\t<h1>로그인</h1>\r\n");
      out.write("\t\t\t\t<span><img src=\"resources/image/logo2.png\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"uEmail\">이메일을 입력하세요</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"uEmail\" name=\"uEmail\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.uEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" aria-describedby=\"emailHelp\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"email@bit.com\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"uPwd\">비밀번호를 입력하세요</label> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" id=\"uPwd\" name=\"uPwd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.uPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"errMsg\" style=\"color: red\">");
      out.print(errMsg);
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div id=\"login-button\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"location.href='#.jsp'\">로 그 인</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"pass-join\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"find_pass.jsp\">비밀번호 찾기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"sns-info\">\r\n");
      out.write("\t\t\t\t\t\t<p>- SNS계정으로 간편 로그인 및 회원가입 -</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"sns-button\">\r\n");
      out.write("\t\t\t\t\t\t<!-- KAKAO Login Start -->\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:kakaoLogin()\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"resources/image/kakao.png\" alt=\"kakao-login\"></a>\r\n");
      out.write("\t\t\t\t\t\t<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\twindow.Kakao.init(\"c231490eabe1939333889bb44ba46f21\");\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tfunction kakaoLogin() {\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.Kakao.Auth.login({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t scope:'profile, account_email, gender',\t//받아올 정보\r\n");
      out.write("\t\t\t\t\t\t\t\t\t success: function(authObj) {\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t console.log(authObj);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t window.Kakao.API.request({\t\t// 로그인 후에 받아올 유저의 정보\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\turl:'/v2/user/me',\t\t// 로그인한 사용자의 정보를 받아오는 url\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \tsuccess: res => {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \t\tconst kakao_account = res.kakao_account;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \t\tconsole.log(kakao_account);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t}</script>\r\n");
      out.write("\t\t\t\t\t\t<!-- KAKAO Login End -->\r\n");
      out.write("\t\t\t\t\t\t<!-- Naver Login Start -->\r\n");
      out.write("\t\t\t\t\t\t");

							String clientId = "tjFd03HRfNwCYRcx8l_F";//애플리케이션 클라이언트 아이디값";
						String redirectURI = URLEncoder.encode("http://localhost:9999/project/index.jsp", "UTF-8");
						SecureRandom random = new SecureRandom();
						String state = new BigInteger(130, random).toString();
						String apiURL = "https://nid.naver.com/oauth2.0/authorize?response_type=code";
						apiURL += "&client_id=" + clientId;
						apiURL += "&redirect_uri=" + redirectURI;
						apiURL += "&state=" + state;
						session.setAttribute("state", state);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(apiURL);
      out.write("\"><img src=\"resources/image/naver.png\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<!-- 토큰삭제 : https://nid.naver.com/oauth2.0/token?grant_type=delete&client_id=tjFd03HRfNwCYRcx8l_F&client_secret=W8CiIlnkbB&access_token=sMM761xU5GSC846U0Q&state=639377487032869747063967426466487713134&service_provider=NAVER -->\r\n");
      out.write("\t\t\t\t\t\t<!-- Naver Login End -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<!------- loginEnd -------> <!------- footerStart -------> <footer\r\n");
      out.write("\t\tid=\"footer\">\r\n");
      out.write("\t\t<section id=\"bottom\" class=\"clearfix\">\r\n");
      out.write("\t\t\t<div class=\"phone\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<span>1599-2121</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>평일 10:00 - 18:00</p>\r\n");
      out.write("\t\t\t\t<p>(점심시간 13:00 - 14:00 제외·주말/공휴일 제외)</p>\r\n");
      out.write("\t\t\t\t<ul class=\"sns\">\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fab fa-facebook\"></i></li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fab fa-instagram\"></i></li>\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fab fa-youtube\"></i></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"service\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"sevName\">해요소개</li>\r\n");
      out.write("\t\t\t\t\t<li>회사소개</li>\r\n");
      out.write("\t\t\t\t\t<li>채용안내</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"sevName\">고객안내</li>\r\n");
      out.write("\t\t\t\t\t<li>이용안내</li>\r\n");
      out.write("\t\t\t\t\t<li>안전정책</li>\r\n");
      out.write("\t\t\t\t\t<li>예상금액</li>\r\n");
      out.write("\t\t\t\t\t<li>전문가소개</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"sevName\">전문가안내</li>\r\n");
      out.write("\t\t\t\t\t<li>이용안내</li>\r\n");
      out.write("\t\t\t\t\t<li>전문가가이트</li>\r\n");
      out.write("\t\t\t\t\t<li>전문가가입</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"sevName\">고객센터</li>\r\n");
      out.write("\t\t\t\t\t<li>공지사항</li>\r\n");
      out.write("\t\t\t\t\t<li>자주묻는질문</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section id=\"bottomtxt\">\r\n");
      out.write("\t\t\t<p>(주)해요모바일은 통신판매중개자로서 통신판매의 당사자가 아니며 개별 판매자가 제공하는 서비스에 대한 이행,\r\n");
      out.write("\t\t\t\t계약사항 등과 관련한 의무와 책임은 거래당사자에게 있습니다.</p>\r\n");
      out.write("\t\t\t<p>상호명:(주)해요모바일 · 대표이사:1조 · 개인정보책임관리자:1조 · 주소:서울특별시 마포구 거구장, 지하\r\n");
      out.write("\t\t\t\t1층(커틀 타워)</p>\r\n");
      out.write("\t\t\t<p>사업자등록번호:111-22-34323 · 통신판매업신고증:제 2015-서울강남-00567 호 · 직업정보제공사업\r\n");
      out.write("\t\t\t\t신고번호:서울청 제 2019-21호</p>\r\n");
      out.write("\t\t\t<p>고객센터:1599-2121 · 이메일:heayo@heayo.com</p>\r\n");
      out.write("\t\t\t<p class=\"copy\">Copyright heayo Web Inc. All Rights Reserved.</p>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</footer> <!------- footerEND -------> </wrap>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
